### ISSUE TITLE
Unable to connect gamehost after dedi being stale for long time

### ISSUE THREAD

**Issue by hellchickens** [project-fika/Fika-Dedicated#13]
**Describe the bug**
Playing client can't connect dedicated hosted game after dedicated client was running too long (~ >8h, maybe less)

**To Reproduce**
1. Launch dedicated client
2. Play a raid on it (not sure if it is needed) 
3. Leave dedi running 8+  hours unattended (e.g. overnight)
4.  Launch raid on exactly that dedi client

**Expected behavior**
Raid is launched and clients can connect into it

**Screenshots**
![image](https://github.com/user-attachments/assets/39a9f53c-3579-4d96-a776-a37687920651)
![image](https://github.com/user-attachments/assets/6ea3e34f-761f-4f00-818a-244d6bcfb29f)

**Log files**
Client logs 
[Player.log](https://github.com/user-attachments/files/16709155/Player.log)
[LogOutput.log](https://github.com/user-attachments/files/16709165/LogOutput.log)

Dedi client + server
[LogOutput.log](https://github.com/user-attachments/files/16709216/LogOutput.log)
[server-2024-08-22.log](https://github.com/user-attachments/files/16709224/server-2024-08-22.log)
[2024.08.21_23-02-12_0.14.9.1.30626 traces.log](https://github.com/user-attachments/files/16709246/2024.08.21_23-02-12_0.14.9.1.30626.traces.log)

**Desktop (please complete the following information):**
Win 11 pro 23H2 both dedi and client
SPT 3.9.8
Fika server 2.2.8
Fika plugin 0.9.8995.14684
Fika dedicated plugin 1.0.4

**Additional context**
Tried on LAN and openVPN networks - behavior is same, so suppose things not in it. 
Haven't noticed 25565 opened when dedi started to wait connections.

**Comment by Lacyway** [comment]
You are running a lot of mods that should not be used on a dedi.
Please remove all mods, leave it running for a while and see if you can reproduce. My client has been alive for over 4 days straight as we speak so I suspect a mod is causing your problems.

**Comment by hellchickens** [comment]
> You are running a lot of mods that should not be used on a dedi. Please remove all mods, leave it running for a while and see if you can reproduce. My client has been alive for over 4 days straight as we speak so I suspect a mod is causing your problems.

Shall I get rid of ALL of them or a can leave SAIN + waypoints + bigbrain, looting bots and deHazardifier?

**Comment by Lacyway** [comment]
You can leave `SAIN + waypoints + bigbrain, looting bots`, remove the others. That way you have a similar setup to me.
General guidelines (still on our discord...) is to *always* try without mods first. >90% of our reports are caused by mods. While I do want to ensure compatibility, I need to know whether it's a core issue or not before I start investigating due to bad past experiences.

**Comment by hellchickens** [comment]
Same behavior, left only SAIN + waypoints + bigbrain, looting bots on dedi:
Client logs:
[LogOutput.log](https://github.com/user-attachments/files/16724679/LogOutput.log)
[Player.log](https://github.com/user-attachments/files/16724683/Player.log)

Dedi logs:
[2024.08.22_21-47-51_0.14.9.1.30626 traces.log](https://github.com/user-attachments/files/16724704/2024.08.22_21-47-51_0.14.9.1.30626.traces.log)
[LogOutput.log](https://github.com/user-attachments/files/16724709/LogOutput.log)
[server-2024-08-23.log](https://github.com/user-attachments/files/16724717/server-2024-08-23.log)
![111](https://github.com/user-attachments/assets/683dbf2c-b143-4f29-ab5a-f91fee89169b)

**Comment by Lacyway** [comment]
Next step is to run it with graphics and observe what happens when you can't connect in the game window.

**Comment by hellchickens** [comment]
Thanks to wireshark and netstat I've managed to catch the problem. It was because of "automatic backend detection" and 2 networks without route between them. Dedicated client expected other client to use VPN network but "autodetection" on gaming client decided to route through LAN (or it was how server responded?), but there was nothing listening that IP. Problem can be resolved by hard binding all IPS in every possible config or to adjust routing. Anyways, solved.
