### ISSUE TITLE
[ENHANCEMENT] Crash dedi when loading unsupported mods

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Dedicated#14]

**Comment by ArchangelWTF** [comment]
List of mods to blacklist:
* Amands Graphics (com.Amanda.Graphics)
* More Checkmarks (VIP.TommySoucy.MoreCheckmarks)
* EFT Api (com.kmyuhkyuk.EFTApi)
* Game Panel HUD (com.kmyuhkyuk.GamePanelHUDCore)

Maybe more? These are the most commonly loaded on the dedi that shouldn't be run there.

**Comment by hood-ok** [comment]
@ArchangelWTF I currently use `MoreCheckmarks` on a dedicated client. Not for any purpose but because it's synced via `modsync` mod from the server. Would you suggest what kind of problem it may produce?

**Comment by ArchangelWTF** [comment]
> @ArchangelWTF I currently use `MoreCheckmarks` on a dedicated client. Not for any purpose but because it's synced via `modsync` mod from the server. Would you suggest what kind of problem it may produce?

It's a client mod that was reported to not work with headless during it's unloading phase, we're blacklisting these in 3.10 right away so that we stop having support requests about people loading graphic / client mods that shouldn't be loaded on the dedicated.

**Comment by ArchangelWTF** [comment]
It's debatable if we want to add plugins that have sync modules built in, such as both Visceral mods as well as Borkels considering the host(Dedicated) would have to recognize those mods in order to stay in sync with other clients.

Friendly PMC's can be added although I feel that the issue with that also exists on a normal host/client situation, that plugin just needs a fix imo

**Comment by TmYNooB** [comment]
> It's debatable if we want to add plugins that have sync modules built in, such as both Visceral mods as well as Borkels considering the host(Dedicated) would have to recognize those mods in order to stay in sync with other clients.

Afaik they are at least not syncing "dismembered limbs" and "dead bodies" and how they fell to 100%. But as said, they should be harmless, except for performance maybe, so keeping/allowing them shouldn't be a problem.
