### ISSUE TITLE
WebSocket send error: 

### ISSUE THREAD

**Issue by Rantol** [project-fika/Fika-Dedicated#17]
Need help installed dll Fika-Dedicated on the PC on the local network. When loading, the map and game gives a constant message “[Error : Telemetry] WebSocket send error: The current state of the connection is not Open.” in red and standard color.
Mods: 
![image](https://github.com/user-attachments/assets/d40b6793-7914-4b51-92a4-9727cd1370d3)

**Comment by trippyone** [comment]
Please open a support ticket in our discord and provide the logs.
