### ISSUE TITLE
Unable to start more than 2 dedicated hosts simultaneously, unable to correctly read the airdrop location

### ISSUE THREAD

**Issue by yyxxceshi** [project-fika/Fika-Dedicated#41]
After the latest testing, if a dedicated host with a value greater than 1 is selected in the configuration file, the configuration file can be generated normally. However, it is not possible to start two at the same time; only one dedicated host is running. If someone has already started a game session using a dedicated host, others will not be able to select and start a dedicated host anymore. But in previous versions, this was possible, and the host could appear in two game sessions. Additionally, there is an issue where if a game session is started using a dedicated host, the marker for airdrops on the dynamic map is incorrect, and the correct airdrop location cannot be read. I hope this can be addressed, thank you.

**Comment by shibdib** [comment]
Dynamic map is a mod so you'd need to talk to the mod maker.

If you have multiple dedi's on the same machine you need to give each of them a unique port in the fika config file.

**Comment by yyxxceshi** [comment]
@echo off
if NOT EXIST ".\BepInEx\plugins\Fika.Dedicated.dll" (
    echo Could not find 'Fika.Dedicated.dll', please install the dedicated plugin before starting the client.
    pause
) else (
    start "" EscapeFromTarkov.exe -token=675095a30001cf47514e2f73 -config={"BackendUrl":"http://10.26.0.2:6969","Version":"live"} -batchmode -nographics --enable-console true & exit
)

In the configuration file, no related configuration about the port was found. In previous versions, a dedicated host would start one, but it could take effect in two or more game sessions.

**Comment by Lacyway** [comment]
Please use our Discord
